### ISSUE TITLE
编译通不过

### ISSUE THREAD

**Issue by guoqj** [Walkud/JudyBridge#2]

**Comment by guoqj** [comment]
Could not find method alwaysCompileJava() for arguments [true] on object of type com.zly.judy.plugin.ConfigExtension.

**Comment by Walkud** [comment]
请在项目根目录build.gradle文件中检查gradle插件依赖的版本是否为0.4.0
classpath 'com.zly.judy:judy-plugin:0.4.0'

**Comment by guoqj** [comment]
没有路由跳转么

**Comment by Walkud** [comment]
目前版本的路由是自行实现，传参都是自行控制，可参照Demo，后续版本会考虑实现路由功能
