### ISSUE TITLE
缓存Method导致的异常

### ISSUE THREAD

**Issue by Gavin-ZYX** [Walkud/JudyBridge#3]
问题：Gilde加载图片报错（You cannot start a load for a destroyed activity）
现象：第一次进入页面，页面正常显示。退出后再次进去，就会出现这样的异常。
使用场景：获取Adapter；参数：Context，List

-------

关闭页面后再次进入，这时从缓存中拿到Method已经不符合这次需求。在这种场有引用参数的情况下，这样使用serviceMethodCache的就不大合适了。

**Comment by Walkud** [comment]
大概找到问题在哪里了，我先复现下

**Comment by Walkud** [comment]
这个问题是由于ServiceMethod 持有了调用的实参，又被添加进缓存（引起了内存泄漏），实际调用的参数为第一次传入的参数导致。
已经修复该问题
